version: '3.4'
services:
  x-ray:
    image: 'xray:latest'
    network_mode: "host"
    privileged: true
    restart: always
    command:
       - "uvicorn"
       - "main:app"
       - "--host"
       - "172.17.3.119"
       - "--port"
       - "8003"



