trigger:
- master

stages:
- stage: Basic_Apps
  jobs:
  - job: DeployStandardApps
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
      displayName: "Build Solution"
            
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'XrayLab'
        publishLocation: 'Container'
      displayName: "Publish build result"

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'ComcoreMedical_Azure_Connector'
        appType: 'webApp'
        WebAppName: 'ComcoreMedical-webapp'
        package: '$(Build.ArtifactStagingDirectory)/XRayLab.UI.zip'
      displayName: "Publish ComcoreMedical-webapp"
      

- stage: Python_apps
  jobs:
  - job: DeployACR
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: Docker@2
        displayName: XRay Lab ML API
        inputs:
          command: buildAndPush
          repository: 'xray_ml_api'
          dockerfile: $(Build.Repository.LocalPath)/XRayLab.ML/Dockerfile
          containerRegistry: 'ComcoreMedical_ACR_Connector'
          tags: |
            '1.3v'