trigger:
- master

stages:
- stage: Basic_Apps
  jobs:
  - job: DeployStandardApps
    pool:
      vmImage: 'windows-latest'

    variables:
      solution: '**/*.sln'
      buildPlatform: 'Any CPU'
      buildConfiguration: 'Release'

    steps:
    - task: NuGetToolInstaller@1

    - task: NuGetCommand@2
      inputs:
        restoreSolution: '$(solution)'

    - task: VSBuild@1
      inputs:
        solution: '$(solution)'
        msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactStagingDirectory)"'
        platform: '$(buildPlatform)'
        configuration: '$(buildConfiguration)'
      displayName: "Build Solution"
            
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'XrayLab'
        publishLocation: 'Container'
      displayName: "Publish build result"

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: '$(AZURE_CONNECTOR)'
        appType: 'webApp'
        WebAppName: '$(BUILD_PREFIX)-$(BUILD_SUFIX)'
        package: '$(Build.ArtifactStagingDirectory)/RoboticsPlatform.zip'
      displayName: "Publish $(BUILD_PREFIX)-$(BUILD_SUFIX)"
      

- stage: Python_apps
  jobs:
  - job: DeployACR
    pool:
      vmImage: 'ubuntu-latest'

    steps:
      - task: Docker@2
        displayName: Container -> SignalR Client
        inputs:
          command: buildAndPush
          repository: 'signalr_ros_client'
          dockerfile: $(Build.Repository.LocalPath)/containers/signalRRosClient/Dockerfile
          containerRegistry: $(DOCKER_REGISTRY_CONNECTOR)
          tags: |
            $(tag)